// =============================================================================
//   VirconDoom test harness -- core runtime known-value checks (M2).
//   GREEN = all pass. RED = FIRST FAIL CHECK #N on screen.
//   Reference vectors generated by tools/wadtool.py from exact PC arithmetic.
// =============================================================================

#include "video.h"
#include "string.h"
#include "time.h"
#include "misc.h"
#include "math.h"

#include "port\\doomdefs.h"
#include "port\\gen_assets.h"
#include "port\\gen_checkvals.h"
#include "port\\m_fixed.h"
#include "port\\tables.h"
#include "port\\m_random.h"
#include "port\\m_bbox.h"
#include "port\\z_zone.h"
#include "port\\r_defs.h"
#include "port\\p_setup.h"
#include "port\\r_main.h"
#include "port\\r_gpu.h"
#include "port\\r_segs.h"
#include "port\\r_bsp.h"
#include "port\\p_tick.h"
#include "port\\p_maputl.h"
#include "port\\p_sight.h"

bool AllPassed = true;
int  checkNum  = 0;
int  firstFail = 0;
int  diagExpected = 0;
int  diagActual = 0;

void Check( bool condition )
{
    checkNum++;
    if( !condition )
    {
        AllPassed = false;
        if( firstFail == 0 )
            firstFail = checkNum;
    }
}

void CheckEq( int actual, int expected )
{
    checkNum++;
    if( actual != expected )
    {
        AllPassed = false;
        if( firstFail == 0 )
        {
            firstFail = checkNum;
            diagExpected = expected;
            diagActual = actual;
        }
    }
}

void ShowInt( int x, int y, int value )
{
    int[20] s;
    itoa( value, s, 10 );
    print_at( x, y, s );
}

void main()
{
    int i;

    // --- group 1: FixedMul, must be BIT-EXACT vs PC ((int64)a*b)>>16
    for( i = 0; i < GEN_NUM_MULCASES; i++ )
        CheckEq( FixedMul( gen_mul_a[i], gen_mul_b[i] ), gen_mul_r[i] );

    // --- group 2: FixedDiv, float-based: tolerance grows with quotient
    for( i = 0; i < GEN_NUM_DIVCASES; i++ )
    {
        int r = FixedDiv( gen_div_a[i], gen_div_b[i] );
        int e = gen_div_r[i];
        int diff = r - e;
        if( diff < 0 ) diff = -diff;
        int mag = e; if( mag < 0 ) mag = -mag;
        int tol = 2 + ( mag >> 18 );
        Check( diff <= tol );
    }

    // --- group 3: trig tables byte-exact from upstream tables.c
    for( i = 0; i < GEN_NUM_FSCASES; i++ )
        CheckEq( finesine[ gen_fs_i[i] ], gen_fs_v[i] );
    for( i = 0; i < GEN_NUM_FTCASES; i++ )
        CheckEq( finetangent[ gen_ft_i[i] ], gen_ft_v[i] );
    for( i = 0; i < GEN_NUM_TACASES; i++ )
        CheckEq( tantoangle[ gen_ta_i[i] ], gen_ta_v[i] );

    // finecosine alias
    InitTables();
    CheckEq( finecosine[0], finesine[2048] );
    CheckEq( finecosine[FINEMASK & 8191], finesine[ ( FINEMASK & 8191 ) + 2048 ] );

    // sin^2+cos^2 ~ 1 in fixed (loose): spot angle 1000
    int s = finesine[1000];
    int c = finecosine[1000];
    int one = FixedMul( s, s ) + FixedMul( c, c );
    Check( one > FRACUNIT - 16 && one < FRACUNIT + 16 );

    // --- group 4: angle wraparound conventions used by the port
    angle_t a1 = ANG270;
    angle_t a2 = ANG90;
    Check( a1 + a2 == 0 );                          // 270+90 wraps to 0
    Check( ( ANG180 >> ANGLETOFINESHIFT ) == 4096 ); // logical shift to fine
    CheckEq( ANG45 >> ANGLETOFINESHIFT, 1024 );

    // --- group 5: SlopeDiv
    CheckEq( SlopeDiv( 70000, 70000 ), 2048 );      // (70000<<3)/(70000>>8)=2051 -> capped SLOPERANGE
    CheckEq( SlopeDiv( 35000, 70000 ), 1025 );      // 280000/273
    CheckEq( SlopeDiv( 0, 70000 ), 0 );
    CheckEq( SlopeDiv( 70000, 100 ), SLOPERANGE );  // den < 512 -> SLOPERANGE

    // --- group 6: random ports
    M_ClearRandom();
    CheckEq( P_Random(), 8 );                       // rndtable[1]
    CheckEq( P_Random(), 109 );                     // rndtable[2]
    CheckEq( M_Random(), 8 );
    prndindex = 255;
    CheckEq( P_Random(), 0 );                       // wraps to rndtable[0]

    // --- group 7: bbox
    fixed_t[4] box;
    M_ClearBox( box );
    Check( box[BOXTOP] == MININT && box[BOXLEFT] == MAXINT );
    M_AddToBox( box, 100, 200 );
    M_AddToBox( box, -50, 300 );
    // upstream else-if quirk: while x keeps shrinking BOXLEFT, BOXRIGHT stays MININT
    Check( box[BOXLEFT] == -50 && box[BOXRIGHT] == MININT );
    M_AddToBox( box, 150, 100 );
    Check( box[BOXRIGHT] == 150 && box[BOXBOTTOM] == 100 && box[BOXTOP] == 300 );

    // --- group 8: zone arena
    int used0 = Z_UsedWords();
    int* pa = Z_Malloc( 100, PU_STATIC, NULL );
    int* pb = Z_Malloc( 50, PU_STATIC, NULL );
    Check( pb - pa == 100 );                        // bump layout
    pa[99] = 1234;
    Check( pa[99] == 1234 );
    Z_MarkLevelStart();
    int usedMark = Z_UsedWords();
    int* pc = Z_CallocLevel( 200 );
    Check( pc[0] == 0 && pc[199] == 0 );
    Z_FreeTags( PU_LEVEL, PU_PURGELEVEL );
    CheckEq( Z_UsedWords(), usedMark );

    // --- group 9: baked map data spot checks (embedded ROM vs PC values)
    CheckEq( gen_vertexes[0][0], GEN_CHECK_V0X );
    CheckEq( gen_vertexes[0][1], GEN_CHECK_V0Y );
    CheckEq( gen_vertexes[GEN_NUMVERTEXES-1][0], GEN_CHECK_VLASTX );
    CheckEq( gen_vertexes[GEN_NUMVERTEXES-1][1], GEN_CHECK_VLASTY );
    CheckEq( gen_sectors[0][0], GEN_CHECK_SEC0FLOOR );
    CheckEq( gen_sectors[0][1], GEN_CHECK_SEC0CEIL );
    CheckEq( gen_sectors[0][4], GEN_CHECK_SEC0LIGHT );
    // structural: every seg's vertex/linedef indices in range
    bool segsOk = true;
    for( i = 0; i < GEN_NUMSEGS; i++ )
    {
        if( gen_segs[i][0] < 0 || gen_segs[i][0] >= GEN_NUMVERTEXES ) segsOk = false;
        if( gen_segs[i][1] < 0 || gen_segs[i][1] >= GEN_NUMVERTEXES ) segsOk = false;
        if( gen_segs[i][4] < 0 || gen_segs[i][4] >= GEN_NUMLINEDEFS ) segsOk = false;
    }
    Check( segsOk );
    // every sidedef's sector in range, textures in range
    bool sidesOk = true;
    for( i = 0; i < GEN_NUMSIDEDEFS; i++ )
    {
        if( gen_sidedefs[i][5] < 0 || gen_sidedefs[i][5] >= GEN_NUMSECTORS ) sidesOk = false;
        if( gen_sidedefs[i][2] < 0 || gen_sidedefs[i][2] >= GEN_NUMTEXTURES ) sidesOk = false;
        if( gen_sidedefs[i][3] < 0 || gen_sidedefs[i][3] >= GEN_NUMTEXTURES ) sidesOk = false;
        if( gen_sidedefs[i][4] < 0 || gen_sidedefs[i][4] >= GEN_NUMTEXTURES ) sidesOk = false;
    }
    Check( sidesOk );

    // --- group 10: ASR (branchless arithmetic shift used by the renderer)
    CheckEq( ASR( -17, 4 ), -2 );
    CheckEq( ASR( 17, 4 ), 1 );
    CheckEq( ASR( -1, 12 ), -1 );
    CheckEq( ASR( -65536, 16 ), -1 );
    CheckEq( ASR( 65536, 16 ), 1 );
    CheckEq( ASR( MININT, 16 ), 0xFFFF8000 );
    CheckEq( ASR( -4096, 12 ), -1 );
    CheckEq( ASR( -4097, 12 ), -2 );

    // --- group 11: ULT (unsigned compare emulation)
    Check( ULT( 1, 2 ) );
    Check( !ULT( -1, 0 ) );            // 0xFFFFFFFF is unsigned max
    Check( ULT( 0, -1 ) );
    Check( ULT( ANG180, ANG270 ) );
    Check( !ULT( ANG270, ANG90 ) );

    // --- group 12: R_PointToAngle vs PC reference (viewx=viewy=0)
    viewx = 0;
    viewy = 0;
    for( i = 0; i < GEN_NUM_PTACASES; i++ )
        CheckEq( R_PointToAngle( gen_pta_x[i], gen_pta_y[i] ), gen_pta_r[i] );

    // --- group 13: level load + BSP point location
    P_SetupLevel();
    Check( numvertexes == GEN_NUMVERTEXES );
    Check( segs[0].v1 == &vertexes[ gen_segs[0][0] ] );
    Check( subsectors[0].sector != NULL );
    // every subsector must resolve a sector, all node children valid
    bool ssOk = true;
    for( i = 0; i < numsubsectors; i++ )
        if( subsectors[i].sector == NULL ) ssOk = false;
    Check( ssOk );
    // player 1 start must land in a subsector with a real sector
    int px = 0;
    int py = 0;
    for( i = 0; i < GEN_NUMTHINGS; i++ )
        if( gen_things[i][3] == 1 )
        {
            px = gen_things[i][0] << FRACBITS;
            py = gen_things[i][1] << FRACBITS;
        }
    Check( px != 0 || py != 0 );
    subsector_t* pss = R_PointInSubsector( px, py );
    Check( pss->sector != NULL );
    // E1M1 player start sector 38: floor 0, ceiling 72, light 144
    // (cross-checked against the baked data via a PC-side BSP walk)
    Check( pss->sector->floorheight == 0 );
    Check( pss->sector->ceilingheight == ( 72 << FRACBITS ) );
    Check( pss->sector->lightlevel == 144 );

    // --- group 13b: R_PointInSubsector vs PC BSP walk over the baked nodes
    // (covers the R_PointOnSide slow path with negative node deltas — the
    //  logical-shift bug that put the playsim in wrong sectors)
    for( i = 0; i < GEN_NUM_PISCASES; i++ )
    {
        subsector_t* qss = R_PointInSubsector( gen_pis_x[i], gen_pis_y[i] );
        Check( qss == &subsectors[ gen_pis_ss[i] ] );
        CheckEq( qss->sector->floorheight, gen_pis_floor[i] );
    }

    // --- group 15: M6 baked state machine tables (spot checks vs upstream
    // info.c values: S_PISTOL2 = {SPR_PISG,1,6,{A_FirePistol},S_PISTOL3})
    CheckEq( gen_states[GEN_S_PISTOL1 + 1][ST_FRAME], 1 );
    CheckEq( gen_states[GEN_S_PISTOL1 + 1][ST_TICS], 6 );
    CheckEq( gen_states[GEN_S_PISTOL1 + 1][ST_ACTION], GEN_ACT_A_FirePistol );
    CheckEq( gen_states[GEN_S_NULL][ST_TICS], -1 );
    CheckEq( gen_states[GEN_S_NULL][ST_NEXTSTATE], GEN_S_NULL );
    // troop: doomednum 3001, spawnhealth 60, painchance 200, speed 8
    CheckEq( gen_mobjinfo[GEN_MT_TROOP][MI_DOOMEDNUM], 3001 );
    CheckEq( gen_mobjinfo[GEN_MT_TROOP][MI_SPAWNHEALTH], 60 );
    CheckEq( gen_mobjinfo[GEN_MT_TROOP][MI_PAINCHANCE], 200 );
    CheckEq( gen_mobjinfo[GEN_MT_TROOP][MI_SPEED], 8 );
    CheckEq( gen_mobjinfo[GEN_MT_PLAYER][MI_HEIGHT], 56 * FRACUNIT );
    // every state's sprite/nextstate/action index must be in range
    bool stOk = true;
    for( i = 0; i < GEN_NUMSTATES; i++ )
    {
        if( gen_states[i][ST_SPRITE] < 0
         || gen_states[i][ST_SPRITE] >= GEN_NUMSPRITES ) stOk = false;
        if( gen_states[i][ST_NEXTSTATE] < 0
         || gen_states[i][ST_NEXTSTATE] >= GEN_NUMSTATES ) stOk = false;
        if( gen_states[i][ST_ACTION] < 0
         || gen_states[i][ST_ACTION] >= GEN_NUMACTIONS ) stOk = false;
    }
    Check( stOk );

    // --- group 16: P_CheckSight vs PC reference walk over the baked
    // REJECT + BSP (covers P_DivlineSide quirk semantics, InterceptVector2,
    // slope accumulation, recursion). Vectors pre-screened on the PC to be
    // robust against the float32 FixedDiv deviation.
    for( i = 0; i < GEN_NUM_SIGHTCASES; i++ )
    {
        boolean sr = P_CheckSightRaw( gen_sight_x1[i], gen_sight_y1[i],
                                      gen_sight_z1[i], gen_sight_s1[i],
                                      gen_sight_x2[i], gen_sight_y2[i],
                                      gen_sight_bz[i], gen_sight_tz[i],
                                      gen_sight_s2[i] );
        int sri = 0;
        if( sr ) sri = 1;
        CheckEq( sri, gen_sight_r[i] );
    }

    // --- group 14: projection tables
    R_InitTextureMapping();
    Check( clipangle > 0 );                          // FOV/2 as positive BAM
    Check( xtoviewangle[0] == clipangle );
    Check( xtoviewangle[viewwidth] == -clipangle );
    // viewangletox must be non-increasing and inside [0,viewwidth]
    bool vtOk = true;
    for( i = 1; i < 4096; i++ )
    {
        if( viewangletox[i] > viewangletox[i-1] ) vtOk = false;
        if( viewangletox[i] < 0 || viewangletox[i] > viewwidth ) vtOk = false;
    }
    Check( vtOk );
    // center column maps to ~zero view angle
    int ca = xtoviewangle[centerx];
    if( ca < 0 ) ca = -ca;
    Check( ca < ANG45 / 256 );

    // --- verdict
    while( true )
    {
        if( AllPassed )
        {
            clear_screen( color_green );
            print_at( 240, 160, "VIRCONDOOM CORE ALL GREEN" );
            print_at( 240, 180, "TOTAL CHECKS" );
            ShowInt( 350, 180, checkNum );
        }
        else
        {
            clear_screen( color_red );
            print_at( 180, 120, "CORE FAIL - FIRST FAIL CHECK" );
            ShowInt( 480, 120, firstFail );
            print_at( 180, 150, "EXPECTED" );
            ShowInt( 300, 150, diagExpected );
            print_at( 180, 170, "ACTUAL" );
            ShowInt( 300, 170, diagActual );
            print_at( 180, 200, "TOTAL CHECKS" );
            ShowInt( 330, 200, checkNum );
        }
        end_frame();
    }
}
