// GENERATED by tools/gen_music.py --events -- do not edit
#ifndef GEN_MUSICEV_H
#define GEN_MUSICEV_H

#define MUS_FRAMES_PER_ROW 3
#define MUS_NUMMAPS 9

#define MUS_E1M1_NEV  2332
#define MUS_E1M1_ROWS 1920
embedded int[ MUS_E1M1_NEV ] mus_e1m1_srow = "data\\mus_e1m1_srow.bin";
embedded int[ MUS_E1M1_NEV ] mus_e1m1_dur = "data\\mus_e1m1_dur.bin";
embedded int[ MUS_E1M1_NEV ] mus_e1m1_inst = "data\\mus_e1m1_inst.bin";
embedded int[ MUS_E1M1_NEV ] mus_e1m1_note = "data\\mus_e1m1_note.bin";
embedded int[ MUS_E1M1_NEV ] mus_e1m1_vel = "data\\mus_e1m1_vel.bin";

#define MUS_E1M2_NEV  2036
#define MUS_E1M2_ROWS 3108
embedded int[ MUS_E1M2_NEV ] mus_e1m2_srow = "data\\mus_e1m2_srow.bin";
embedded int[ MUS_E1M2_NEV ] mus_e1m2_dur = "data\\mus_e1m2_dur.bin";
embedded int[ MUS_E1M2_NEV ] mus_e1m2_inst = "data\\mus_e1m2_inst.bin";
embedded int[ MUS_E1M2_NEV ] mus_e1m2_note = "data\\mus_e1m2_note.bin";
embedded int[ MUS_E1M2_NEV ] mus_e1m2_vel = "data\\mus_e1m2_vel.bin";

#define MUS_E1M3_NEV  3749
#define MUS_E1M3_ROWS 5440
embedded int[ MUS_E1M3_NEV ] mus_e1m3_srow = "data\\mus_e1m3_srow.bin";
embedded int[ MUS_E1M3_NEV ] mus_e1m3_dur = "data\\mus_e1m3_dur.bin";
embedded int[ MUS_E1M3_NEV ] mus_e1m3_inst = "data\\mus_e1m3_inst.bin";
embedded int[ MUS_E1M3_NEV ] mus_e1m3_note = "data\\mus_e1m3_note.bin";
embedded int[ MUS_E1M3_NEV ] mus_e1m3_vel = "data\\mus_e1m3_vel.bin";

#define MUS_E1M4_NEV  3105
#define MUS_E1M4_ROWS 3414
embedded int[ MUS_E1M4_NEV ] mus_e1m4_srow = "data\\mus_e1m4_srow.bin";
embedded int[ MUS_E1M4_NEV ] mus_e1m4_dur = "data\\mus_e1m4_dur.bin";
embedded int[ MUS_E1M4_NEV ] mus_e1m4_inst = "data\\mus_e1m4_inst.bin";
embedded int[ MUS_E1M4_NEV ] mus_e1m4_note = "data\\mus_e1m4_note.bin";
embedded int[ MUS_E1M4_NEV ] mus_e1m4_vel = "data\\mus_e1m4_vel.bin";

#define MUS_E1M5_NEV  1464
#define MUS_E1M5_ROWS 3280
embedded int[ MUS_E1M5_NEV ] mus_e1m5_srow = "data\\mus_e1m5_srow.bin";
embedded int[ MUS_E1M5_NEV ] mus_e1m5_dur = "data\\mus_e1m5_dur.bin";
embedded int[ MUS_E1M5_NEV ] mus_e1m5_inst = "data\\mus_e1m5_inst.bin";
embedded int[ MUS_E1M5_NEV ] mus_e1m5_note = "data\\mus_e1m5_note.bin";
embedded int[ MUS_E1M5_NEV ] mus_e1m5_vel = "data\\mus_e1m5_vel.bin";

#define MUS_E1M6_NEV  1625
#define MUS_E1M6_ROWS 1680
embedded int[ MUS_E1M6_NEV ] mus_e1m6_srow = "data\\mus_e1m6_srow.bin";
embedded int[ MUS_E1M6_NEV ] mus_e1m6_dur = "data\\mus_e1m6_dur.bin";
embedded int[ MUS_E1M6_NEV ] mus_e1m6_inst = "data\\mus_e1m6_inst.bin";
embedded int[ MUS_E1M6_NEV ] mus_e1m6_note = "data\\mus_e1m6_note.bin";
embedded int[ MUS_E1M6_NEV ] mus_e1m6_vel = "data\\mus_e1m6_vel.bin";

#define MUS_E1M7_NEV  1336
#define MUS_E1M7_ROWS 3018
embedded int[ MUS_E1M7_NEV ] mus_e1m7_srow = "data\\mus_e1m7_srow.bin";
embedded int[ MUS_E1M7_NEV ] mus_e1m7_dur = "data\\mus_e1m7_dur.bin";
embedded int[ MUS_E1M7_NEV ] mus_e1m7_inst = "data\\mus_e1m7_inst.bin";
embedded int[ MUS_E1M7_NEV ] mus_e1m7_note = "data\\mus_e1m7_note.bin";
embedded int[ MUS_E1M7_NEV ] mus_e1m7_vel = "data\\mus_e1m7_vel.bin";

#define MUS_E1M8_NEV  877
#define MUS_E1M8_ROWS 3040
embedded int[ MUS_E1M8_NEV ] mus_e1m8_srow = "data\\mus_e1m8_srow.bin";
embedded int[ MUS_E1M8_NEV ] mus_e1m8_dur = "data\\mus_e1m8_dur.bin";
embedded int[ MUS_E1M8_NEV ] mus_e1m8_inst = "data\\mus_e1m8_inst.bin";
embedded int[ MUS_E1M8_NEV ] mus_e1m8_note = "data\\mus_e1m8_note.bin";
embedded int[ MUS_E1M8_NEV ] mus_e1m8_vel = "data\\mus_e1m8_vel.bin";

#define MUS_E1M9_NEV  3805
#define MUS_E1M9_ROWS 2748
embedded int[ MUS_E1M9_NEV ] mus_e1m9_srow = "data\\mus_e1m9_srow.bin";
embedded int[ MUS_E1M9_NEV ] mus_e1m9_dur = "data\\mus_e1m9_dur.bin";
embedded int[ MUS_E1M9_NEV ] mus_e1m9_inst = "data\\mus_e1m9_inst.bin";
embedded int[ MUS_E1M9_NEV ] mus_e1m9_note = "data\\mus_e1m9_note.bin";
embedded int[ MUS_E1M9_NEV ] mus_e1m9_vel = "data\\mus_e1m9_vel.bin";

int* mus_srow;
int* mus_dur;
int* mus_inst;
int* mus_note;
int* mus_vel;
int  mus_nev;
int  mus_rows;

// Point the active-track globals at map `m` (1..MUS_NUMMAPS).
void MUS_SelectMap( int m )
{
    if( m == 1 )
    {
        mus_srow = mus_e1m1_srow;  mus_dur  = mus_e1m1_dur;
        mus_inst = mus_e1m1_inst;  mus_note = mus_e1m1_note;
        mus_vel  = mus_e1m1_vel;
        mus_nev  = MUS_E1M1_NEV;  mus_rows = MUS_E1M1_ROWS;
    }
    else if( m == 2 )
    {
        mus_srow = mus_e1m2_srow;  mus_dur  = mus_e1m2_dur;
        mus_inst = mus_e1m2_inst;  mus_note = mus_e1m2_note;
        mus_vel  = mus_e1m2_vel;
        mus_nev  = MUS_E1M2_NEV;  mus_rows = MUS_E1M2_ROWS;
    }
    else if( m == 3 )
    {
        mus_srow = mus_e1m3_srow;  mus_dur  = mus_e1m3_dur;
        mus_inst = mus_e1m3_inst;  mus_note = mus_e1m3_note;
        mus_vel  = mus_e1m3_vel;
        mus_nev  = MUS_E1M3_NEV;  mus_rows = MUS_E1M3_ROWS;
    }
    else if( m == 4 )
    {
        mus_srow = mus_e1m4_srow;  mus_dur  = mus_e1m4_dur;
        mus_inst = mus_e1m4_inst;  mus_note = mus_e1m4_note;
        mus_vel  = mus_e1m4_vel;
        mus_nev  = MUS_E1M4_NEV;  mus_rows = MUS_E1M4_ROWS;
    }
    else if( m == 5 )
    {
        mus_srow = mus_e1m5_srow;  mus_dur  = mus_e1m5_dur;
        mus_inst = mus_e1m5_inst;  mus_note = mus_e1m5_note;
        mus_vel  = mus_e1m5_vel;
        mus_nev  = MUS_E1M5_NEV;  mus_rows = MUS_E1M5_ROWS;
    }
    else if( m == 6 )
    {
        mus_srow = mus_e1m6_srow;  mus_dur  = mus_e1m6_dur;
        mus_inst = mus_e1m6_inst;  mus_note = mus_e1m6_note;
        mus_vel  = mus_e1m6_vel;
        mus_nev  = MUS_E1M6_NEV;  mus_rows = MUS_E1M6_ROWS;
    }
    else if( m == 7 )
    {
        mus_srow = mus_e1m7_srow;  mus_dur  = mus_e1m7_dur;
        mus_inst = mus_e1m7_inst;  mus_note = mus_e1m7_note;
        mus_vel  = mus_e1m7_vel;
        mus_nev  = MUS_E1M7_NEV;  mus_rows = MUS_E1M7_ROWS;
    }
    else if( m == 8 )
    {
        mus_srow = mus_e1m8_srow;  mus_dur  = mus_e1m8_dur;
        mus_inst = mus_e1m8_inst;  mus_note = mus_e1m8_note;
        mus_vel  = mus_e1m8_vel;
        mus_nev  = MUS_E1M8_NEV;  mus_rows = MUS_E1M8_ROWS;
    }
    else if( m == 9 )
    {
        mus_srow = mus_e1m9_srow;  mus_dur  = mus_e1m9_dur;
        mus_inst = mus_e1m9_inst;  mus_note = mus_e1m9_note;
        mus_vel  = mus_e1m9_vel;
        mus_nev  = MUS_E1M9_NEV;  mus_rows = MUS_E1M9_ROWS;
    }
}

#endif
