// GENERATED by tools/wadtool.py -- do not edit
#ifndef GEN_SOUNDS_H
#define GEN_SOUNDS_H

#define GEN_NUMSFX 109
#define GEN_NUMVSOUNDS 62
#define GEN_MUSIC_SOUND -1   // Vircon sound_id of looping music, -1 if none
#define GEN_WAVE_BASE 55   // sound_id of wt_sine (synth_init base), -1 if none
#define GEN_WAVE_COUNT 7   // synth wavetables in WAVE_* order

// forward prototypes for the playsim (defined in s_sound.h, late in
// the TU). Kept here (not doomdefs.h) so the sound-free harness/walls
// ROMs -- which do not include this header -- never see an undefined fn.
// origin: mobj_t* (positional) or NULL (full volume); sec: sector_t*.
void S_StartSound( void* origin, int sfx_id );
void S_StartSoundSector( void* sec, int sfx_id );

// sfxenum_t values (index into gen_sfx_sound / gen_sfx_priority)
#define SFX_NONE 0
#define SFX_PISTOL 1
#define SFX_SHOTGN 2
#define SFX_SGCOCK 3
#define SFX_DSHTGN 4
#define SFX_DBOPN 5
#define SFX_DBCLS 6
#define SFX_DBLOAD 7
#define SFX_PLASMA 8
#define SFX_BFG 9
#define SFX_SAWUP 10
#define SFX_SAWIDL 11
#define SFX_SAWFUL 12
#define SFX_SAWHIT 13
#define SFX_RLAUNC 14
#define SFX_RXPLOD 15
#define SFX_FIRSHT 16
#define SFX_FIRXPL 17
#define SFX_PSTART 18
#define SFX_PSTOP 19
#define SFX_DOROPN 20
#define SFX_DORCLS 21
#define SFX_STNMOV 22
#define SFX_SWTCHN 23
#define SFX_SWTCHX 24
#define SFX_PLPAIN 25
#define SFX_DMPAIN 26
#define SFX_POPAIN 27
#define SFX_VIPAIN 28
#define SFX_MNPAIN 29
#define SFX_PEPAIN 30
#define SFX_SLOP 31
#define SFX_ITEMUP 32
#define SFX_WPNUP 33
#define SFX_OOF 34
#define SFX_TELEPT 35
#define SFX_POSIT1 36
#define SFX_POSIT2 37
#define SFX_POSIT3 38
#define SFX_BGSIT1 39
#define SFX_BGSIT2 40
#define SFX_SGTSIT 41
#define SFX_CACSIT 42
#define SFX_BRSSIT 43
#define SFX_CYBSIT 44
#define SFX_SPISIT 45
#define SFX_BSPSIT 46
#define SFX_KNTSIT 47
#define SFX_VILSIT 48
#define SFX_MANSIT 49
#define SFX_PESIT 50
#define SFX_SKLATK 51
#define SFX_SGTATK 52
#define SFX_SKEPCH 53
#define SFX_VILATK 54
#define SFX_CLAW 55
#define SFX_SKESWG 56
#define SFX_PLDETH 57
#define SFX_PDIEHI 58
#define SFX_PODTH1 59
#define SFX_PODTH2 60
#define SFX_PODTH3 61
#define SFX_BGDTH1 62
#define SFX_BGDTH2 63
#define SFX_SGTDTH 64
#define SFX_CACDTH 65
#define SFX_SKLDTH 66
#define SFX_BRSDTH 67
#define SFX_CYBDTH 68
#define SFX_SPIDTH 69
#define SFX_BSPDTH 70
#define SFX_VILDTH 71
#define SFX_KNTDTH 72
#define SFX_PEDTH 73
#define SFX_SKEDTH 74
#define SFX_POSACT 75
#define SFX_BGACT 76
#define SFX_DMACT 77
#define SFX_BSPACT 78
#define SFX_BSPWLK 79
#define SFX_VILACT 80
#define SFX_NOWAY 81
#define SFX_BAREXP 82
#define SFX_PUNCH 83
#define SFX_HOOF 84
#define SFX_METAL 85
#define SFX_CHGUN 86
#define SFX_TINK 87
#define SFX_BDOPN 88
#define SFX_BDCLS 89
#define SFX_ITMBK 90
#define SFX_FLAME 91
#define SFX_FLAMST 92
#define SFX_GETPOW 93
#define SFX_BOSPIT 94
#define SFX_BOSCUB 95
#define SFX_BOSSIT 96
#define SFX_BOSPN 97
#define SFX_BOSDTH 98
#define SFX_MANATK 99
#define SFX_MANDTH 100
#define SFX_SSSIT 101
#define SFX_SSDTH 102
#define SFX_KEENPN 103
#define SFX_KEENDT 104
#define SFX_SKEACT 105
#define SFX_SKESIT 106
#define SFX_SKEATK 107
#define SFX_RADIO 108

// gen_sfx_sound[sfxenum] = Vircon SPU sound_id, or -1 if absent
embedded int[GEN_NUMSFX] gen_sfx_sound = "data\\sfx_sound.bin";
embedded int[GEN_NUMSFX] gen_sfx_priority = "data\\sfx_priority.bin";

#endif
