// GENERATED by tools/wadtool.py -- do not edit
#ifndef GEN_ASSETS_H
#define GEN_ASSETS_H

// GPU texture ids (order must match the ROM XML <textures> list)
#define TEXID_SHEET0 0
#define TEXID_SHEET1 1
#define TEXID_SHEET2 2
#define TEXID_SHEET3 3
#define TEXID_WHITE 4
#define GEN_NUMSHEETS 4

#define GEN_NUMTEXTURES 125
#define GEN_NUMFLATS 54
#define GEN_SKYTEXTURE 59
#define GEN_SKYFLATNUM 53

#define GEN_NUMVERTEXES 467
#define GEN_NUMSECTORS 85
#define GEN_NUMSIDEDEFS 648
#define GEN_NUMLINEDEFS 475
#define GEN_NUMSSECTORS 237
#define GEN_NUMSEGS 732
#define GEN_NUMNODES 236
#define GEN_NUMTHINGS 138
#define GEN_NUMBLOCKMAP 3461

// texinfo: sheet,x,y,w,h per texture; flatinfo: sheet,x,y per flat
embedded int[GEN_NUMTEXTURES][5] gen_texinfo = "data\\texinfo.bin";
embedded int[GEN_NUMFLATS][3] gen_flatinfo = "data\\flatinfo.bin";
embedded int[GEN_NUMFLATS] gen_flatavg = "data\\flatavg.bin";

// trig tables (fixed_t / BAM)
embedded int[10240] finesine = "data\\finesine.bin";
embedded int[4096] finetangent = "data\\finetangent.bin";
embedded int[2049] tantoangle = "data\\tantoangle.bin";

// map lumps, word-widened (layouts: see tools/wadtool.py header)
embedded int[GEN_NUMVERTEXES][2] gen_vertexes = "data\\e1m1_vertexes.bin";
embedded int[GEN_NUMSECTORS][7] gen_sectors = "data\\e1m1_sectors.bin";
embedded int[GEN_NUMSIDEDEFS][6] gen_sidedefs = "data\\e1m1_sidedefs.bin";
embedded int[GEN_NUMLINEDEFS][7] gen_linedefs = "data\\e1m1_linedefs.bin";
embedded int[GEN_NUMSSECTORS][2] gen_ssectors = "data\\e1m1_ssectors.bin";
embedded int[GEN_NUMSEGS][6] gen_segs = "data\\e1m1_segs.bin";
embedded int[GEN_NUMNODES][14] gen_nodes = "data\\e1m1_nodes.bin";
embedded int[GEN_NUMTHINGS][5] gen_things = "data\\e1m1_things.bin";
embedded int[GEN_NUMBLOCKMAP] gen_blockmap = "data\\e1m1_blockmap.bin";

#endif
