// -----------------------------------------------------------------------------
//  mus_player.h -- full-polyphony event player for level music, faithful to the
//  original bake_music render (tools/wadtool.py) but driven live by port/synth.h.
//
//  Every note is one event played via synth_play_timed (no mono reduction, no
//  chords dropped). Four instruments match the approved musictest.c timbres:
//    0 lead   -- plain square (melody + harmony)
//    1 bass   -- square, a touch louder
//    2 kick   -- low triangle punch with a pitch drop (defined thump)
//    3 snhat  -- short crisp noise (snare + hats)
//
//  Requires synth.h to be included first (with the host's SYNTH_VOICES /
//  SYNTH_CHANNEL_BASE window). Event data is generated by
//  tools/gen_music.py --events into gen_musicev.h.
//
//  Frame model: MUS_TickFrame advances exactly one 60 Hz frame; the caller runs
//  it once per elapsed vsync (S_MusicUpdate) for drift-free tempo.
// -----------------------------------------------------------------------------
#ifndef MUS_PLAYER_H
#define MUS_PLAYER_H

#include "synth.h"
#include "gen_musicev.h"

Instrument mi_lead;
Instrument mi_bass;
Instrument mi_kick;
Instrument mi_snhat;
Instrument*[4] mi_inst;

int  mp_cur;                       // cursor into the srow-sorted event arrays
int  mp_row;                       // current row
int  mp_timer;                     // frames until the next row
bool mp_playing;

// Build the instrument set. Call after synth_init (does not need presets).
void MUS_Init()
{
    synth_patch( &mi_lead, WAVE_SQUARE, 0.14, 1, 0, 1.0, 2 );   // melody/harmony
    synth_patch( &mi_bass, WAVE_SQUARE, 0.18, 1, 0, 1.0, 2 );   // louder square
    synth_patch( &mi_kick, WAVE_TRIANGLE, 0.34, 0, 6, 0.0, 4 ); // low punch...
    mi_kick.pitch_slide = -0.9;                                 // ...with pitch drop
    synth_patch( &mi_snhat, WAVE_NOISE, 0.20, 0, 4, 0.0, 2 );   // short noise
    mi_snhat.curve = 0.5;

    mi_inst[0] = &mi_lead;
    mi_inst[1] = &mi_bass;
    mi_inst[2] = &mi_kick;
    mi_inst[3] = &mi_snhat;

    mp_cur = 0;
    mp_row = 0;
    mp_timer = 0;
    mp_playing = false;
}

// (Re)start the track from the top with a clean voice state.
void MUS_Start()
{
    synth_panic();
    mp_cur = 0;
    mp_row = 0;
    mp_timer = 0;
    mp_playing = true;
}

// Silence the music (kills sounding voices; player parked).
void MUS_Stop()
{
    mp_playing = false;
    synth_panic();
}

// Advance the player exactly one 60 Hz frame.
void MUS_TickFrame()
{
    if( mp_playing && mp_timer <= 0 )
    {
        // fire every event that starts on this row (full polyphony; the synth's
        // allocator steals the lowest-amplitude voice if ever over budget).
        while( mp_cur < MUS_E1M1_NEV && mus_e1m1_srow[ mp_cur ] == mp_row )
        {
            int inst = mus_e1m1_inst[ mp_cur ];
            float v = (float)mus_e1m1_vel[ mp_cur ] / 127.0;
            synth_play_timed( mi_inst[ inst ], mus_e1m1_note[ mp_cur ], v,
                              mus_e1m1_dur[ mp_cur ] );
            mp_cur++;
        }
        mp_row++;
        mp_timer = MUS_FRAMES_PER_ROW;
        if( mp_row >= MUS_E1M1_ROWS )    // loop the whole track
        {
            mp_row = 0;
            mp_cur = 0;
        }
    }
    mp_timer--;
    synth_update();
}

#endif
